# Generated by Django 3.0.2 on 2020-01-15 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200109_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, help_text='Enter Birthday in YYYY-MM-DD Format', null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Enter City', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Enter Valid Email ID', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(help_text='Enter First Name', max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='default.png', help_text='Upload Profile Pic', upload_to='contacts', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Enter Last Name', max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, default='', help_text='Enter Mobile Number', max_length=11, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
