# Generated by Django 3.0.2 on 2020-01-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Registered User', 'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
