# Generated by Django 3.0.2 on 2020-01-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200109_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
