# Generated by Django 3.0.2 on 2020-01-15 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200114_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Activation Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activation_deadline',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Activation Deadline'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, help_text='Enter Your Birthday in YYYY-MM-DD Format', null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Enter Your City', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Enter Valid Email ID', max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_sent',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Email Sent'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Enter Your First Name', max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default.png', help_text='Upload Your Profile Pic', upload_to='users', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=35, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Enter Your Last Name', max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, default='', help_text='Enter Your Mobile Number', max_length=11, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='User Agent'),
        ),
    ]
