# Generated by Django 3.0.2 on 2020-01-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200115_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Region'),
        ),
    ]
